title: PopcornMeter
description: Software artifact for a Movie Recommendation Website that provides personalized movie suggestions based on user preferences. Includes user profiles, a recommendation engine, OMDb API integration, relational database design, and a watchlist feature.
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
